name: Deploy FTP (dev e prod)

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

concurrency:
  group: ftp-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev:
    name: Deploy DEV
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enviar para DEV
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          # Se ao logar você já cai DENTRO de "pegacorrida.anvy.com.br",
          # troque para: /public_html/dev/
          server-dir: /senhas.anvy.com.br/dev/
          state-name: ftp-state-dev.json
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.md

  deploy-prod:
    name: Deploy PROD
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enviar para PROD
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /senhas.anvy.com.br/prod/
          state-name: ftp-state-prod.json
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.md